#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jonathan Rosenblatt

# Short bio or description (displayed in the header)
description: Stats, R, and possibly beach volley.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://www.gravatar.com/avatar/609c7f878c4030e90d27b4f7be921b02

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: johnros@bgu.ac.il
  github: johnros
  linkedin: johnros
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: johnros2013
  stackoverflow: users/379859/johnros# your stackoverflow profile, e.g. "users/50476/bart-kiers"
  orcid: 0000-0003-3116-1782


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: jonathanrosenblattsblog

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-63813109-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://johnros.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create atom-feed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

categories: [static_page]
